# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#a87569"

# Title color for boxes
theme[title]="#684c59"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#a63650"

# Background color of selected item in processes box
theme[selected_bg]="#6d4745"

# Foreground color of selected item in processes box
theme[selected_fg]="#e3a68c"

# Color of inactive/disabled text
theme[inactive_fg]="#6b6566"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#684c59"

# Box outline and divider line color
theme[cpu_box]="#f28171"
theme[mem_box]="#f28171"
theme[net_box]="#f28171"
theme[proc_box]="#c24f57"
theme[div_line]="#e3a68c"

# Gradient for all meters and graphs
theme[temp_start]="#e3a68c"
theme[temp_mid]="#f28171"
theme[temp_end]="#c24f57"


theme[cpu_start]="#e3a68c"
theme[cpu_mid]="#f28171"
theme[cpu_end]="#a63650"


theme[free_start]="#e3a68c"
theme[free_mid]="#f28171"
theme[free_end]="#a63650"


theme[cached_start]="#e3a68c"
theme[cached_mid]="#f28171"
theme[cached_end]="#a63650"


theme[available_start]="#e3a68c"
theme[available_mid]="#f28171"
theme[available_end]="#a63650"


theme[used_start]="#e3a68c"
theme[used_mid]="#f28171"
theme[used_end]="#a63650"


theme[download_start]="#e3a68c"
theme[download_mid]="#f28171"
theme[download_end]="#a63650"


theme[upload_start]="#e3a68c"
theme[upload_mid]="#f28171"
theme[upload_end]="#a63650"
