-- Generated by scripts/hypr2lua.
-- Source: omarchy-caroline-skyline-theme/hyprland.conf

local activeBorderColor = "rgb(684c59)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
    },
  },
  group = {
    col = {
      border_active = activeBorderColor,
    },
  },
  decoration = {
    rounding = 18,
    blur = {
      enabled = true,
      size = 2,
      passes = 4,
      noise = 0.0,
    },
    shadow = {
      enabled = true,
      range = 18,
      render_power = 6,
      color = "rgba(c24f57dc)",
      color_inactive = "rgba(111111ef)",
      offset = "2 2",
    },
  },
})

hl.curve("bezier01", { type = "bezier", points = { { 0.65, 0 }, { 0.35, 1 } } })

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 5,
  bezier = "bezier01",
  style = "popin",
})
hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 4,
  bezier = "bezier01",
  style = "slidefade",
})
